"""Generate a runnable Locust load-test file for RAG HTTP endpoints."""

from __future__ import annotations

import logging

logger = logging.getLogger(__name__)

_LOCUST_TEMPLATE = '''"""
ragfallback load test — generated by ragfallback.mlops.locust_template
Run with: locust -f {output_path} --host {endpoint}
"""
import random
from locust import HttpUser, task, between

SHORT_QUERIES = [
    "billing policy", "refund process", "API limits",
    "authentication token", "rate limiting",
]
LONG_QUERIES = [
    "Please explain in detail the billing and refund policy. Provide a comprehensive answer with examples if possible.",
    "Please explain in detail how API rate limiting works and what the thresholds are. Provide a comprehensive answer with examples if possible.",
    "Please explain in detail the authentication flow including token refresh. Provide a comprehensive answer with examples if possible.",
]
OOD_QUERIES = [
    "What is the weather in Tokyo?",
    "How do I bake sourdough bread?",
    "Who won the FIFA World Cup in 1998?",
]

class RAGLoadUser(HttpUser):
    wait_time = between(0.5, 2.0)

    @task(1)
    def health_check(self):
        with self.client.get("/health", catch_response=True) as resp:
            if resp.status_code != 200:
                resp.failure(f"Health check failed: {{resp.status_code}}")

    @task(4)
    def short_keyword_query(self):
        payload = {{"query": random.choice(SHORT_QUERIES)}}
        with self.client.post("/query", json=payload, catch_response=True) as resp:
            if resp.status_code != 200:
                resp.failure(f"Short query failed: {{resp.status_code}}")

    @task(2)
    def long_nl_query(self):
        payload = {{"query": random.choice(LONG_QUERIES)}}
        with self.client.post("/query", json=payload, catch_response=True) as resp:
            if resp.status_code != 200:
                resp.failure(f"Long NL query failed: {{resp.status_code}}")

    @task(1)
    def out_of_domain_query(self):
        payload = {{"query": random.choice(OOD_QUERIES)}}
        with self.client.post("/query", json=payload, catch_response=True) as resp:
            # OOD queries may return 200 with low confidence — that's expected
            if resp.status_code not in (200, 422):
                resp.failure(f"OOD query failed: {{resp.status_code}}")
'''


def generate_locustfile(output_path: str, endpoint: str) -> None:
    """Write a Locust scenario to ``output_path`` targeting ``endpoint`` as default host hint."""
    content = _LOCUST_TEMPLATE.format(output_path=output_path, endpoint=endpoint)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    logger.info(
        "Locust file written to %s. Run with: locust -f %s --host %s",
        output_path,
        output_path,
        endpoint,
    )
